export default {
  register: 'Account/Register',
  login: 'Account/CheckIn',
  sendotp: 'Account/SendOTP',
  verifyotp: 'Account/VerifyOTP',
  checkin: 'Account/CheckIn',
  checkout: 'Account/CheckOut',
  weeklypoints: 'Account/WeeklyPoints',
  getPromotional: 'Event/ShowPromotionEvent',
  postPromotional: 'Event/EnterPromotionEvent',
  getRedeemPoints: 'Points/GetRedeemPoints',
  postRedeemPoints: 'Points/RedeemPoints',
  getOffers: 'Event/ShowOffers',
  postOffers: 'Event/EnterOffer',
  getPointsHistory: 'Points/PointsHistory',
  updateProfile: 'Account/EditProfile',
  getProfile: 'Account/GetProfile',
  requestNumber: 'Account/EditPhoneNumber',
  getStores: 'Stores/GetStoresNearBy',
  viewAllStores:'Stores/ViewAllStores'
};
