import {heightScale, height, fontScale} from '../../helpers';
import {colors, Fonts} from '../../constants';
export const Styles = {
  container: {},
  button: {borderRadius: heightScale(100)},
  gradient: {paddingVertical: heightScale(5), marginTop: heightScale(10)},
  checkinText: {color: colors.White},
  arrowViewRight: {
    height: heightScale(38),
    width: heightScale(60),
    borderTopRightRadius: 100,
    borderBottomRightRadius: 100,
    backgroundColor: colors.White,
  },
  arrowViewLeft: {
    height: heightScale(38),
    width: heightScale(60),
    borderTopLeftRadius: 100,
    borderBottomLeftRadius: 100,
    backgroundColor: colors.White,
  },
  icon: {color: colors.lightBlue3, fontSize: fontScale(30)},
  memberText: {fontSize: fontScale(14)},
  signupText: {color: colors.lightBlue4, fontSize: fontScale(14)},
  pointTextView: {borderWidth: 1, borderColor: colors.lightBlue},
  howWorksTextSteps: {fontSize: fontScale(13), paddingVertical: 5},
  howWorksText: {color: colors.lightBlue3, fontSize: fontScale(13)},
  howWorksView: {
    width: '100%',
    borderBottomWidth: 1,
    borderColor: colors.lightBlue,
  },
  iconImage: {
    height: heightScale(20),
    width: heightScale(20),
    marginLeft: heightScale(10),
  },
  gradView: {height: heightScale(100), width: '19%'},
  bigGrad: {width: '23%'},
  grad: {marginTop: 1},
  xPontsText: {color: colors.lightBlue3},
  round: {
    height: fontScale(30),
    width: fontScale(30),
    borderRadius: 100,
    borderWidth: 3,
    borderColor: colors.lightBlue4,
    backgroundColor: colors.White,
  },
  pointsonText: {color: colors.White, fontSize: fontScale(10)},
  daysText: {fontSize: fontScale(10)},
  vLine: {borderLeftWidth: 1, borderColor: colors.lightBlue},
  innverPointsView: {width: '100%'},
  pointCenterView: {alignItems: 'center', width: '100%'},
  loader: {width: '100%', height: heightScale(100)},
  extraHeight: {height: heightScale(10)},
  pointHeading: {fontSize: fontScale(14)},
};
